//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue_Script
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.Chapters = new HashSet<Chapter>();
            this.Characters = new HashSet<Character>();
            this.Scenes = new HashSet<Scene>();
            this.Settings = new HashSet<Setting>();
            this.Unsorteds = new HashSet<Unsorted>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Chapter> Chapters { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
        public virtual ICollection<Scene> Scenes { get; set; }
        public virtual ICollection<Setting> Settings { get; set; }
        public virtual ICollection<Unsorted> Unsorteds { get; set; }
    }
}
