//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blue_Script
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;
	using System.Web.Mvc;
    
    public partial class Scene
    {
        public Scene()
        {
            this.Characters = new HashSet<Character>();
        }
		[HiddenInput(DisplayValue = false)]
        public int ID { get; set; }

        public string Name { get; set; }

		[DataType(DataType.MultilineText)]
        public string Notes { get; set; }

        public Nullable<int> SettingID { get; set; }
    
        public virtual Setting Setting { get; set; }
        public virtual ICollection<Character> Characters { get; set; }
    }
}
